### ISSUE TITLE
Put file as train/valid/test on git-lfs or other easily downloaded link for integration with huggingface 

### ISSUE THREAD

**Issue by cstorm125** [nakhunchumpolsathien/ThaiSum#1]
I'm trying to integrate ThaiSum to huggingface/datasets. One of the key things to do is to have an easily accessible download link of a compressed file (data.zip) where inside are train, validation and test files.

Example: huggingface/datasets#981

Currently ThaiSum needs to be downloaded via Google Drive, which is not very convenient for this purpose.
I'm wondering if you would consider hosting it on git-lfs (or other more easily accessible links) instead.

**Comment by nakhunchumpolsathien** [comment]
Hi @cstorm125 , 

I uploaded the zip file contains train/valid/test on https://nk-us.oss-us-west-1.aliyuncs.com/thaisum.zip . I am not sure if I did it correctly. Please check.

**Comment by cstorm125** [comment]
I found a free solution of uploading it to the Internet Archive:
https://archive.org/details/thaisum_datasets

**Comment by cstorm125** [comment]
add huggingface/datasets PR for reference:
https://github.com/huggingface/datasets/pull/1090
